### ISSUE TITLE
依赖cloudopt-next-eventbus时，也必须同时依赖lettuce-core，否则启动打印类找不到。

### ISSUE THREAD

**Issue by qianqian78** [cloudoptlab/cloudopt-next#43]
<dependency>
      <groupId>net.cloudopt.next</groupId>
      <artifactId>cloudopt-next-eventbus</artifactId>
      <version>${nextVersion}</version>
</dependency>

java.lang.NoClassDefFoundError: io/lettuce/core/pubsub/RedisPubSubAdapter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:802)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:700)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:623)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at net.cloudopt.next.core.Classer.loadClass(Classer.kt:169)
	at net.cloudopt.next.core.Classer.fillClass(Classer.kt:365)
	at net.cloudopt.next.core.Classer.processJarFile(Classer.kt:340)
	at net.cloudopt.next.core.Classer.fillClasses(Classer.kt:235)
	at net.cloudopt.next.core.Classer.scanPackage(Classer.kt:127)
	at net.cloudopt.next.core.Classer.scanPackageByAnnotation(Classer.kt:83)
	at net.cloudopt.next.web.NextServer.scan(NextServer.kt:208)
	at net.cloudopt.next.web.NextServer.run(NextServer.kt:277)

**Comment by T-baby** [comment]
怀疑是自动扫描时把 RedisMQProvider 自动加载进去了，我会看看如何优化扫描加载这个部分。

**Comment by T-baby** [comment]
已在开发分支中修复。

https://github.com/cloudoptlab/cloudopt-next/commit/9c54cd7d85e2ab99f19703ce891d1a1142cc831f

**Comment by T-baby** [comment]
已合并 #50
