### ISSUE TITLE
启动报出Thread blocked

### ISSUE THREAD

**Issue by qianqian78** [cloudoptlab/cloudopt-next#67]
2022-07-05 11:55:26.675 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2813 ms, time limit is 2000 ms
2022-07-05 11:55:27.681 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 3820 ms, time limit is 2000 ms
2022-07-05 11:55:28.722 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 4861 ms, time limit is 2000 ms
2022-07-05 11:55:29.731 [vertx-blocked-thread-checker] WARN  io.vertx.core.impl.BlockedThreadChecker - Thread Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 5866 ms, time limit is 2000 ms
io.vertx.core.VertxException: Thread blocked
	at java.base@11.0.2/java.io.WinNTFileSystem.getBooleanAttributes(Native Method)
	at java.base@11.0.2/java.io.File.exists(File.java:820)
	at java.base@11.0.2/java.io.WinNTFileSystem.lambda$listRoots$1(WinNTFileSystem.java:600)
	at java.base@11.0.2/java.io.WinNTFileSystem$$Lambda$247/0x00000008004c3440.test(Unknown Source)
	at java.base@11.0.2/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base@11.0.2/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base@11.0.2/java.util.BitSet$1BitSetSpliterator.forEachRemaining(BitSet.java:1302)
	at java.base@11.0.2/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:699)
	at java.base@11.0.2/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base@11.0.2/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base@11.0.2/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:550)
	at java.base@11.0.2/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base@11.0.2/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:517)
	at java.base@11.0.2/java.io.WinNTFileSystem.listRoots(WinNTFileSystem.java:601)
	at java.base@11.0.2/java.io.File.listRoots(File.java:1791)
	at app//io.vertx.ext.web.handler.impl.StaticHandlerImpl.setRoot(StaticHandlerImpl.java:590)
	at app//io.vertx.ext.web.handler.impl.StaticHandlerImpl.setWebRoot(StaticHandlerImpl.java:453)
	at app//net.cloudopt.next.web.NextServerVerticle.start(NextServerVerticle.kt:220)
	at app//io.vertx.kotlin.coroutines.CoroutineVerticle$start$1.invokeSuspend(CoroutineVerticle.kt:50)
	at app//kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at app//kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at app//io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:229)
	at app//kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:94)
	at app//kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:332)
	at app//kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at app//kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:25)
	at app//kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:110)
	at app//kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:126)
	at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at app//kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at app//kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:47)
	at app//kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at app//io.vertx.kotlin.coroutines.CoroutineVerticle.start(CoroutineVerticle.kt:48)
	at app//io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at app//io.vertx.core.impl.DeploymentManager$$Lambda$234/0x00000008004c7c40.handle(Unknown Source)
	at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:96)
	at app//io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:59)
	at app//io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:37)
	at app//io.vertx.core.impl.EventLoopContext$$Lambda$116/0x000000080037e840.run(Unknown Source)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:164)
	at app//io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at app//io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at app//io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at app//io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at app//io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.2/java.lang.Thread.run(Thread.java:834)

**Comment by qianqian78** [comment]
window 10 上运行，报的错
